development: &development
  image: ghost:latest
  ports:
    - 2368:2368
  environment:
    NODE_ENV: development
    VIRTUAL_HOST: http://localhost
    VIRTUAL_PORT: 2368
  volumes:
    - ./ghost-override:/ghost-override

production:
  <<: *development
  environment:
    NODE_ENV: production
    VIRTUAL_HOST: http://you.blog.url
    VIRTUAL_PORT: 2368