development: &development
  image: ghost:latest
  ports:
    - 2368:2368
  environment:
    NODE_ENV: development
    VIRTUAL_HOST: http://localhost
    VIRTUAL_PORT: 2368
    GHOST_CONTENT: /home/gabriel/Development/personal/blog
  volumes:
    - ./content/themes:/usr/src/ghost/content/themes
    - ./content/apps:/usr/src/ghost/content/apps
    - ./content/images:/usr/src/ghost/content/images
    - ./content/data:/usr/src/ghost/content/data
    - ./config:/var/lib/ghost

production:
  <<: *development
  environment:
    NODE_ENV: production
    VIRTUAL_HOST: http://you.blog.url
    VIRTUAL_PORT: 2368